apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democid
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jonathan1503/POC-CICD
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
